// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06.Models;

namespace Mission06.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    partial class MovieApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission06.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("applicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("applicationID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            applicationID = 1,
                            Category = "Action",
                            Director = "John McTernan",
                            Edited = false,
                            Lent = "Cade Gardanier",
                            Notes = "Best Christmas Movie",
                            Rating = "PG-13",
                            Title = "Die Hard",
                            Year = (short)1988
                        },
                        new
                        {
                            applicationID = 2,
                            Category = "Sports",
                            Director = "Boaz Yakin",
                            Edited = false,
                            Lent = "Cade Gardanier",
                            Notes = "Good film",
                            Rating = "PG",
                            Title = "Remember The Titans",
                            Year = (short)2000
                        },
                        new
                        {
                            applicationID = 3,
                            Category = "War",
                            Director = "Steven Spielberg",
                            Edited = true,
                            Lent = "Cade Gardanier",
                            Notes = "might want it edited",
                            Rating = "R",
                            Title = "Saving Private Ryan",
                            Year = (short)1998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
